services:
  llamacpp:
    image: ghcr.io/ggerganov/llama.cpp:server
    command:
      - -m
      - /models/test-model.gguf
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - -c
      - "8192"
      - -ngl
      - "4"
    ports:
      - "8091:8080"
    volumes:
      - "./models:/models"
    restart: unless-stopped
